baseURL = 'https://aixdaily.github.io/'
languageCode = 'en-us'
title = 'Ai x Daily'
theme = 'dream'

# Add these if not present
[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"

[params]
  custom_css = ["/css/custom.css"]